FROM golang
WORKDIR /go/src/github.com/polyverse/
COPY #SCRAMBLER_DIR
WORKDIR ./scrambler
RUN go get -v .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /polyscripting/php-scrambler
COPY #TOKENIZER_DIR
COPY . /polyscripting/