name: Publish 7.2 Apache Image 
on: 
        push:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Polyscripting Tools Apache Docker Hub
        run: ./build.sh -p
        shell: bash
        working-directory: ./polyscripting/
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUBLISH_PERSONAL_ACCESS_TOKEN }}
      - name: Publish 7.2 Git Package Repository
        run: ./build.sh -g
        shell: bash
        working-directory: ./polyscripting/
